### PR TITLE
fix: Minimum GraphQL v16 support

### LINKED ISSUE #1009: Fix for graphql 16: GraphQLNonNull cannot be invoked without 'new'
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `nexus@1.1.0` for the project I'm working on.

Nexus wasn't working anymore with graphql version 16.0.0 nor 16.0.1 

My error message was
```
Class constructor GraphQLNonNull cannot be invoked without 'new'
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/nexus/src/definitions/wrapping.ts b/node_modules/nexus/src/definitions/wrapping.ts
index 9af7565..c60aa00 100644
--- a/node_modules/nexus/src/definitions/wrapping.ts
+++ b/node_modules/nexus/src/definitions/wrapping.ts
@@ -246,10 +246,10 @@ export function rewrapAsGraphQLType(baseType: GraphQLNamedType, wrapping: NexusF
   let finalType: GraphQLType = baseType
   wrapping.forEach((wrap) => {
     if (wrap === 'List') {
-      finalType = GraphQLList(finalType)
+      finalType = new GraphQLList(finalType)
     } else if (wrap === 'NonNull') {
       if (!isNonNullType(finalType)) {
-        finalType = GraphQLNonNull(finalType)
+        finalType = new GraphQLNonNull(finalType)
       }
     } else {
       throw new Unreachable(wrap)
```
It happened because of this PR https://github.com/graphql/graphql-js/pull/2906

### PR DESCRIPTION
**Pull request by tgriesser**
Fixes #1009

### CODE REVIEW

**Comment by darrylyoung** [comment]
Thanks for the quick fix with this, @tgriesser. Will the non-beta `1.2.0` be releasing soon or is it recommended to use `next`?

**Comment by tgriesser** [comment]
Just use `next` for now if you can, probably won't get around to cutting `1.2.0` for a few weeks.

**Comment by tgriesser** [comment]
It is in a runtime sense, but not fully from a type-safety standpoint yet, that'll require #1017 - was working on that the other day and still needed to fix up some of the integration tests. Will keep working on it this week

**Comment by kjkent** [comment]
Amazing; thanks for the update, it's appreciated.

**Pull request merged**
