### PR TITLE
feat: add plugin support for inputObjectType

### PR DESCRIPTION
**Pull request by filipstefansson**
### Motivation

There's currently no way of extending `inputObjectType` through a plugin like we can do with `objectType`. I'm writing a validation plugin and [I need to "hook in" to the type for input objects](https://github.com/filipstefansson/nexus-validate/pull/9).

### Implementation

I copied the implementation for `NexusGenPluginTypeConfig` and renamed it to `NexusGenPluginInputTypeConfig`.

###  Example

```ts
// my-plugin.ts
const inputObjectdDefTypes = printedGenTyping({
  name: 'pluginName',
  type: 'string',
  ...
});

const myPlugin = () => {
  return plugin({
    ...
    inputObjectTypeDefTypes: inputObjectdDefTypes,
  });
}
```

```ts
// schema.ts
const MyInput = inputObjectType({
  ...
  pluginName: 'hello world',
});
```

Let me know if this is relevant and if my solution works!

### CODE REVIEW

**Comment by tgriesser** [comment]
That plugin idea seems great! Want to fix up the failing snapshot tests and maybe add a new test covering this, and we can look to get this merged?

**Comment by filipstefansson** [comment]
> That plugin idea seems great! Want to fix up the failing snapshot tests and maybe add a new test covering this, and we can look to get this merged?

Awesome. I'll do that!

**Comment by filipstefansson** [comment]
@tgriesser updated snapshots and added a test to make sure the plugin can take the new `inputObjectTypeDefTypes` property without throwing errors or warning in the console.

Let me know what you think!

**Comment by tgriesser** [comment]
Looks great, thanks!

**Pull request merged**
