### PR TITLE
fix: sync should gen artifact logic with what docs say

### PR DESCRIPTION
**Pull request by astroash**
…ather than only when in development

 #883

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
@tgriesser I'm fine with this change, any objections? It is technically a breaking change. Maybe we should just change the docs.

**Comment by astroash** [comment]
@jasonkuhrt just for reference, this change is in line with how the documentation describes generated artifacts

https://nexusjs.org/docs/guides/generated-artifacts#introduction

**Comment by jasonkuhrt** [comment]
@astroash true, but might be different than observed behaviour so far.

**Comment by tgriesser** [comment]
Yeah this change seems fine.

**Pull request merged**
